views:
    lwlock_count:
        title: Количество сессий с LWLock
        description: Отображает количество сессий с LWLock
        sql: "select count(*) from pg_catalog.pg_stat_activity where wait_event_type='LWLock';"

    pg_stat_activity:
        title: Статистика активности
        description: Отображает статистику активности бэкэндов
        sql: "SELECT * FROM pg_catalog.pg_stat_activity LIMIT (:limit) OFFSET (:offset);"

    pg_stat_database:
        title: Статистика баз данных
        description: Отображает статистику баз данных
        sql: "SELECT * FROM pg_catalog.pg_stat_database LIMIT (:limit) OFFSET (:offset);"

    list_long_sessions:
        title: Сессии с долгим временем выполнения запроса
        description: Отображает сессии с долгим временем выполнения запроса
        sql: "SELECT
  pid,
  user,
  pg_stat_activity.query_start,
  now() - pg_stat_activity.query_start AS query_time,
  query,
  state,
  wait_event_type,
  wait_event
FROM pg_stat_activity
WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';"
