"""machine agregate status

Revision ID: 28470b81d018
Revises: b3fa40ccdee4
Create Date: 2023-11-18 17:41:46.377132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "28470b81d018"
down_revision: Union[str, None] = "b3fa40ccdee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    agregate_status = sa.Enum("free", "busy", "broken", name="agregatestatus")
    agregate_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agregates",
        "status",
        existing_type=sa.VARCHAR(),
        type_=agregate_status,
        postgresql_using="status::agregatestatus",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    agregate_status = sa.Enum("free", "busy", "broken", name="agregatestatus")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agregates",
        "status",
        existing_type=agregate_status,
        type_=sa.VARCHAR(),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    agregate_status.drop(op.get_bind())
