"""add tasks, machine, agregates

Revision ID: 59d94a7aad8e
Revises: e36c2b41eeda
Create Date: 2023-11-18 07:23:59.187440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59d94a7aad8e"
down_revision: Union[str, None] = "e36c2b41eeda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agregates",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_location", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "machines",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_location", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agregate_suitable_machines",
        sa.Column("agregate_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agregate_id"],
            ["agregates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.PrimaryKeyConstraint("agregate_id", "machine_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("asignee_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("starting", sa.DateTime(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("work_volume", sa.Float(), nullable=True),
        sa.Column("payment_coefficient", sa.Float(), nullable=True),
        sa.Column("fuel_consumption", sa.Float(), nullable=True),
        sa.Column("agregate_depth", sa.Float(), nullable=True),
        sa.Column("agregate_working_speed", sa.Float(), nullable=True),
        sa.Column("agregate_solvent_consumption", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asignee_id"],
            ["user_data.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_agregate",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("agregate_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agregate_id"],
            ["agregates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "agregate_id"),
    )
    op.create_table(
        "task_comments",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_data.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_machine",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "machine_id"),
    )
    op.create_table(
        "task_status_history",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_data.user_id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "user_id", "id"),
    )
    op.create_table(
        "task_suitable_agregates",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("agregate_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agregate_id"],
            ["agregates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "agregate_id"),
    )
    op.create_table(
        "task_suitable_machines",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "machine_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_suitable_machines")
    op.drop_table("task_suitable_agregates")
    op.drop_table("task_status_history")
    op.drop_table("task_machine")
    op.drop_table("task_comments")
    op.drop_table("task_agregate")
    op.drop_table("tasks")
    op.drop_table("agregate_suitable_machines")
    op.drop_table("machines")
    op.drop_table("agregates")
    # ### end Alembic commands ###
