"""reinit alembic

Revision ID: 6a634bbdfead
Revises:
Create Date: 2023-11-19 00:54:32.287350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a634bbdfead"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role")
    op.add_column("tasks", sa.Column("description", sa.String(), nullable=True))
    op.drop_column("tasks", "attachments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("attachments", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("tasks", "description")
    op.create_table(
        "user_role",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="user_role_pkey"),
        sa.UniqueConstraint("name", name="user_role_name_key"),
    )
    # ### end Alembic commands ###
