"""machine enum status 2

Revision ID: b3fa40ccdee4
Revises: 384cbadd653b
Create Date: 2023-11-18 17:39:41.379466

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b3fa40ccdee4"
down_revision: Union[str, None] = "384cbadd653b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
