"""add tasks, machine, agregates 3

Revision ID: ce4db0b88f46
Revises: 6796b6a34214
Create Date: 2023-11-18 07:34:37.954641

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ce4db0b88f46"
down_revision: Union[str, None] = "6796b6a34214"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
