"""task status

Revision ID: fc51c09aaadc
Revises: 28470b81d018
Create Date: 2023-11-18 17:53:33.375625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc51c09aaadc"
down_revision: Union[str, None] = "28470b81d018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    task_stasus_type = sa.Enum(
        "draft", "assigned", "in_progress", "paused", "completed", "canceled", name="taskstatuses"
    )
    task_stasus_type.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(),
        type_=task_stasus_type,
        postgresql_using="status::taskstatuses",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    task_stasus_type = sa.Enum(
        "draft", "assigned", "in_progress", "paused", "completed", "canceled", name="taskstatuses"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=task_stasus_type,
        type_=sa.VARCHAR(),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    task_stasus_type.drop(op.get_bind())
